using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WVA_Compulink_Integration.MatchFinder
{
    class ProductCrossRefDict
    {
        public static Dictionary<string, string> GetCrossRefDict()
        {
            Dictionary<string, string> CrossRefDictionary = new Dictionary<string, string>
            {
                { "Air Optix Aq Mo              Ciba Vision",       "AIR OPTIX (OLD) SPHERE - 6 PK" },
                { "AqComfPlusDali               Trial",             "......*TRIAL* DAILIES AQUA-COMFORT - 5 CT" },
                { "1 Day AV Moist                90 Pack",          "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1 Day AV Moist                Ninety Pack",      "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1 Day AV Moist                Trial",            "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1 Day Define                  Ninety Pack",      "1 DAY ACUVUE DEFINE W/ LACREON 90PK" },
                { "1 Day Define                  Thirty Pack",      "1 DAY ACUVUE DEFINE W/ LACREON 30PK" },
                { "1 Day Define                  Trial",            "........*TRIAL* 1 DAY DEFINE W/ LACREON 5PK" },
                { "1D    AV Moist                90 Pack",          "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D    AV Moist                90 Packs",         "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D    AV Moist                Ninety Pack",      "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D    AV Moist                Thirty Pack",      "1 DAY ACUVUE MOIST - 30 PK" },
                { "1D    AV Moist                Trial",            "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1D    AV Moist                Trial, Final",     "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1D AV Moist                   90 Pack",          "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D AV Moist                   Ninety Pack",      "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D AV Moist                   Thirty Pack",      "1 DAY ACUVUE MOIST - 30 PK" },
                { "1D AV Moist                   Trial",            "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1D AV Moist                   Trial, Final",     "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1D AV Moist                   Trials",           "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "1D AV Moist MF                90 Pack",          "1 DAY ACUVUE MOIST MULTIFOCAL 90PK" },
                { "1D AV Moist MF                Ninety Pack",      "1 DAY ACUVUE MOIST MULTIFOCAL 90PK" },
                { "1D AV Moist MF                Thirty Pack",      "1 DAY ACUVUE MOIST MULTIFOCAL 30PK" },
                { "1D AV Moist MF                Trial",            "........*TRIAL* 1 DAY MOIST MF *TRIAL* 5PK" },
                { "1D AVMoist Asti               30 Pack",          "1 DAY MOIST FOR ASTIG - 30 PK" },
                { "1D AVMoist Asti               30 Packs",         "1 DAY MOIST FOR ASTIG - 30 PK" },
                { "1D AVMoist Asti               90 Packs",         "1 DAY MOIST FOR ASTIGMATISM - 90 PK" },
                { "1D AVMoist Asti               Ninety Pack",      "1 DAY MOIST FOR ASTIGMATISM - 90 PK" },
                { "1D AVMoist Asti               Ninety Pack, Fi",  "1 DAY MOIST FOR ASTIGMATISM - 90 PK" },
                { "1D AVMoist Asti               Thirty Pack",      "1 DAY MOIST FOR ASTIG - 30 PK" },
                { "1D AVMoist Asti               Trial",            "........*TRIAL* 1 DAY MOIST FOR ASTIG - 5PK" },
                { "1day AV  moist                90 Pack",          "1 DAY ACUVUE MOIST MULTIFOCAL 90PK" },
                { "Acuvue Oasys                  Trial",            "........*TRIAL* OASYS - 6 PACK *TRIALS*" },
                { "Air Op Astig                  6 Packs",          "AIR OPTIX FOR ASTIGMATISM - 6 PK" },
                { "Air Op Astig                  Six Packs",        "AIR OPTIX FOR ASTIGMATISM - 6 PK" },
                { "Air Op Astig                  Six Packs, Ciba",  "AIR OPTIX FOR ASTIGMATISM - 6 PK" },
                { "Air Op Astig                  Six Packs, Fina",  "AIR OPTIX FOR ASTIGMATISM - 6 PK" },
                { "Air Op Astig                  Trial",            "........*TRIAL* AIR OPTIX ASTIGMATISM - 2PK" },
                { "Air Op Astig                  Trials",           "........*TRIAL* AIR OPTIX ASTIGMATISM - 2PK" },
                { "Air Op Mo Color               2pk",              "AIR OPTIX AQUA COLORS (TWO) - 2 PK" },
                { "Air Op Mo Color               Six Pack",         "AIR OPTIX AQUA COLORS - 6 PACK" },
                { "Air Op Mo Color               Six Packs",        "AIR OPTIX AQUA COLORS - 6 PACK" },
                { "Air Op Mo Color               Trial",            "........*TRIAL* AIR OPTIX COLOR - 6 CT" },
                { "Air Op Mo Hydra               Six Packs",        "AIR OPTIX PLUS HYDRAGLYDE - 6PK" },
                { "Air Opt Nt&Day                Six Packs",        "AIR OPTIX NIGHT & DAY - 6 PACK" },
                { "Air Opt Nt&Day                Trail",            "........*TRIAL* AIR OPTIX NIGHT & DAY - 1PK" },
                { "Air Opt Nt&Day                Trial",            "........*TRIAL* AIR OPTIX NIGHT & DAY - 1PK" },
                { "Air Opt Nt&Day                Trials",           "........*TRIAL* AIR OPTIX NIGHT & DAY - 1PK" },
                { "Air Opt Nt&Day,               Trial",            "........*TRIAL* AIR OPTIX NIGHT & DAY - 1PK" },
                { "Air Optix Aq Mo               6 Packs",          "AIR OPTIX (OLD) SPHERE - 6 PK" },
                { "Air Optix Aq Mo               Six Packs",        "AIR OPTIX (OLD) SPHERE - 6 PK" },
                { "Air Optix Aq Mo               Six Packs, Fina",  "AIR OPTIX (OLD) SPHERE - 6 PK" },
                { "Air Optix Aq Mo               Trial",            "........*TRIAL* AIR OPTIX AQUA 3 PKS" },
                { "Air Optix Aq Mo               Trial, Final",     "........*TRIAL* AIR OPTIX AQUA 3 PKS" },
                { "Air Optix Hydra                Six Packs",       "AIR OPTIX PLUS HYDRAGLYDE - 6PK" },
                { "Air Optix Hydra               Six Packs",        "AIR OPTIX PLUS HYDRAGLYDE - 6PK" },
                { "Air Optix Hydra               Six Packs, Fina",  "AIR OPTIX PLUS HYDRAGLYDE - 6PK" },
                { "Air Optix Hydra               Six Packs, fina",  "AIR OPTIX PLUS HYDRAGLYDE - 6PK" },
                { "Air Optix Hydra               Trial",            "........*TRIAL* AIR OPTIX HYDRAGLYDE 3 PKS" },
                { "Air Optix Hydra               Trial,",           "........*TRIAL* AIR OPTIX HYDRAGLYDE 3 PKS" },
                { "Air Optix Hydra               Trials",           "........*TRIAL* AIR OPTIX HYDRAGLYDE 3 PKS" },
                { "Air Optix MF                  6 Packs",          "AIR OPTIX MULTIFOCAL - 6 PK" },
                { "Air Optix MF                  Six Packs",        "AIR OPTIX MULTIFOCAL - 6 PK" },
                { "Air Optix MF                  Trial",            "........*TRIAL* AIR OPTIX MULTIFOCAL 2PK" },
                { "Air Optix MF                  Trial1",           "........*TRIAL* AIR OPTIX MULTIFOCAL 2PK" },
                { "Air Optix toric               Six Packs",        "AIR OPTIX FOR ASTIGMATISM - 6 PK" },
                { "AirOpMultif                   Six Packs",        "AIR OPTIX MULTIFOCAL - 6 PK" },
                { "Aq Comf Dailies               90 Pack",          "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "Aq Comf Dailies               Ninety Pack",      "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqCmPlus DL MF                Ninety P",         "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqCmPlus DL MF                Ninety Pack",      "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqCmPlus DL MF                Thirty Pack",      "DAILIES AQUACOMFORT PLUS MF - 30 PK" },
                { "AqCmPlus DL MF                Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "AqCmPlus DL Tor               Ninety Pack",      "DAILIES AQUA COMF PLUS TORIC - 90PK" },
                { "AqCmPlus DL Tor               Ninety Pack, Fi",  "DAILIES AQUA COMF PLUS TORIC - 90PK" },
                { "AqCmPlus DL Tor               Thirty Pack",      "DAILIES AQUA COMF PLUS TORIC - 30PK" },
                { "AqCmPlus DL Tor               Trial",            "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqCmPlus DL Tor               Trials",           "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqComfDAILY MF                Ninety Pack",      "DAILIES AQUACOMFORT PLUS MF - 90 PK" },
                { "AqComfDAILY MF                Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "AqComfMF                      Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "AqComfPlusDalie                Ninety Pack",     "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               90 Pack",          "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               90 Packs",         "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               Ninety Pack",      "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               Ninety Pack,",     "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               Ninety Pack, Fi",  "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               Ninety Packs",     "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "AqComfPlusDalie               Thirty Pack",      "DAILIES AQUACOMFORT PLUS - 30 PACK" },
                { "AqComfPlusDalie               Thirty Pack, Ni",  "DAILIES AQUACOMFORT PLUS - 30 PACK" },
                { "AqComfPlusDalie               Trail",            "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqComfPlusDalie               Trial",            "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqComfPlusDalie               Trial1",           "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqComfPlusDalie               Trials",           "........*TRIAL* DAILIES AQUA PLUS TORIC-5PK" },
                { "AqComfPlusMF                  Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "Aqua MF dailies               Ninety Pack",      "DAILIES AQUACOMFORT PLUS - 90 PACK" },
                { "Aqua MF dailies               Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "AQUACOMFORT MF                Trial",            "........*TRIAL* DAILIES AQUACOMFORT MF -5CT" },
                { "AV 0asys Presby               Six Packs",        "OASYS FOR PRESBYOPIA 6 PACK" },
                { "AV 0asys Presby               Trial",            "........*TRIAL* OASYS PRESBYOPIA FULL PACK" },
                { "AV 2                          Six Packs",        "ACUVUE 2 - 6 PK" },
                { "Av moist                      Thirty Pack",      "1 DAY ACUVUE MOIST - 30 PK" },
                { "AV Moist                      Trial",            "........*TRIAL* ACUVUE 1 DAY MOIST - 10 PK" },
                { "AV Oas Astg 1 D               30 Pack",          "OASYS 1-DAY FOR ASTIGMATISM 30PK" },
                { "AV Oas Astg 1 D               Thirty Pack",      "OASYS 1-DAY FOR ASTIGMATISM 30PK" },
                { "AV Oas Astg 1 D               Trial",            "........*TRIAL* OASYS 1-DAY ASTIGMATISM 5PK" },
                { "AV OasAstig 1da               Trial",            "........*TRIAL* OASYS 1-DAY ASTIGMATISM 5PK" },
                { "AV Oasys                      12 Packs",         "OASYS - 12 PACK" },
                { "AV Oasys                      Trial",            "........*TRIAL* OASYS - 6 PACK *TRIALS*" },
                { "AV Oasys                      Twelve Pack",      "OASYS - 12 PACK" },
                { "AV Oasys                      Twentyfour Pac",   "OASYS - 24 PK" },
                { "AV Oasys                      Twentyfour Pack",  "OASYS - 24 PK" },
                { "AV Oasys 1 Day                Trail",            "........*TRIAL* OASYS - 6 PACK *TRIALS*" },
                { "AV Oasys 1 Day                Trial",            "........*TRIAL* OASYS - 6 PACK *TRIALS*" },
                { "AV Oasys 1 Day                Trials",           "........*TRIAL* OASYS - 6 PACK *TRIALS*" },
                { "AV Oasys Astig                6 Packs",          "OASYS FOR ASTIGMATISM - 6 PK" },
                { "AV Oasys Astig                Six Packs",        "OASYS FOR ASTIGMATISM - 6 PK" },
                { "AV Oasys Astig                Trial",            "........*TRIAL* OASYS FOR ASTIGMATISM SNGL" },
                { "AV Oasys1daytor               Thirty Pack",      "OASYS 1-DAY FOR ASTIGMATISM 30PK" },
                { "AV OasysAstig                 Trial",            "........*TRIAL* OASYS FOR ASTIGMATISM SNGL" },
                { "AV Vita                       Six Packs",        "ACUVUE VITA - 6 PACK" },
                { "AV vita                       Six Packs",        "ACUVUE VITA - 6 PACK" },
                { "AV Vita                       Trial",            "........*TRIAL* VITA - 6 PACK *TRIALS*" },
                { "AV Vita                       Twelve Pack",      "ACUVUE VITA - 12 PACK" },
                { "AV Vitality                   Six Packs",        "AVAIRA VITALITY 6-PK" },
                { "AV Vitality                   Trial",            "........*TRIAL* AVAIRA VITALITY SINGLE" },
                { "AV2                           Six Packs",        "ACUVUE 2 - 6 PK" },
                { "AV2                           Trial",            "........*TRIAL* ACUVUE 2-FULL PACK *TRIALS*" },
                { "Avaira vitality               Six Packs",        "AVAIRA VITALITY 6-PK" },
                { "Avaira Vitality               Trial",            "........*TRIAL* AVAIRA VITALITY SINGLE" },
                { "AVOAYSISTORIC                 Trial",            "........*TRIAL* OASYS FOR ASTIGMATISM SNGL" },
                { "B&L Multifocal                Six Packs",        "SOFLENS MULTIFOCAL - 6 PACK" },
                { "Bifinity toric                Trial",            "........*TRIAL* BIOFINITY TORIC *TRIAL*" },
                { "Biofinity                     Six Packs",        "BIOFINITY - 6 PK" },
                { "Biofinity                     Trial",            "........*TRIAL* BIOFINITY SINGLE" },
                { "Biofinity  XR                 Six Packs",        "BIOFINITY TORIC XR - 6 PK" },
                { "Biofinity  XR                 Trial",            "........*TRIAL* BIOFINITY XR SINGLE *TRIAL*" },
                { "Biofinity Energ               Six Packs",        "BIOFINITY ENERGYS - 6 PK" },
                { "Biofinity Energ               Trial",            "........*TRIAL* BIOFINITY ENERGYS SINGLE" },
                { "Biofinity MF                  Six Packs",        "BIOFINITY MULTIFOCAL - 6 PACK" },
                { "Biofinity MF                  Trial",            "........*TRIAL* BIOFINITY MULTIFOCAL" },
                { "Biofinity multi               Six Packs",        "BIOFINITY MULTIFOCAL - 6 PACK" },
                { "Biofinity multi               Trial",            "........*TRIAL* BIOFINITY MULTIFOCAL" },
                { "Biofinity T XR                Six Packs",        "BIOFINITY TORIC XR - 6 PK" },
                { "Biofinity T XR                Trial",            "........*TRIAL* BIOFINITY TORIC XR *TRIAL*" },
                { "Biofinity Toric               Six Packs",        "BIOFINITY TORIC - 6 PK" },
                { "Biofinity Toric               Six Packs, Fina",  "BIOFINITY TORIC - 6 PK" },
                { "Biofinity Toric               Trial",            "........*TRIAL* BIOFINITY TORIC *TRIAL*" },
                { "Biofinity Toric               Trials",           "........*TRIAL* BIOFINITY TORIC *TRIAL*" },
                { "BiofinityMF                   Six Packs",        "BIOFINITY MULTIFOCAL - 6 PACK" },
                { "BiofinityMF                   Trial",            "........*TRIAL* BIOFINITY MULTIFOCAL" },
                { "BiofinityXR                   Trial",            "........*TRIAL* BIOFINITY TORIC XR *TRIAL*" },
                { "BiofinToric XR                Six Packs",        "BIOFINITY TORIC XR - 6 PK" },
                { "BiofinToric XR                Trial",            "........*TRIAL* BIOFINITY TORIC XR *TRIAL*" },
                { "BiofinToric XR                Trials",           "........*TRIAL* BIOFINITY TORIC XR *TRIAL*" },
                { "BioMed 55                     Six Packs",        "BIOMEDICS 55 PREMIER - 6 PK" },
                { "BioMed 55                     Trial",            ".....…*TRIAL* BIOMEDICS 55 ASPHERIC - 3CT" },
                { "BioMed 55prem                 Six Packs",        "BIOMEDICS 55 PREMIER - 6 PK" },
                { "BioMed 55Premie               Six Packs",        "BIOMEDICS 55 PREMIER - 6 PK" },
                { "BioMed Premier                Six Packs",        "BIOMEDICS 55 PREMIER - 6 PK" },
                { "BioMed Toric                  Six Packs",        "BIOMEDICS TORIC - 6 PACK" },
                { "BioMed Toric                  Trial",            "........*TRIAL* BIOMEDICS TORIC" },
                { "BioMed55                      Six Packs",        "BIOMEDICS 55 PREMIER - 6 PK" },
                { "Biomedics  XC                 Six Packs",        "BIOMEDICS XC - 6 PK" },
                { "BioTru Daily                  Ninety Pack",      "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTru Daily                  Trial",            "........*TRIAL* BIOTRUE ONEDAY - 5 PACK" },
                { "BioTru Daily MF               Ninety Pack",      "BIOTRUE 1DAY FOR PRESBYOPIA - 90 PK" },
                { "BioTru Daily MF               Thirty Pack",      "BIOTRUE 1DAY FOR PRESBYOPIA - 30 PK" },
                { "BioTru Daily MF               Trial",            "........*TRIAL* BIOTRUE FOR PRESBYOPIA-5 PK" },
                { "BioTrue astg                  Ninety Pack",      "BIOTRUE ONEDAY TOR-90PK(3 THIRTIES)" },
                { "BioTrue astg                  Trial",            "........*TRIAL* BIOTRUE 1DAY TORIC - 5 PACK" },
                { "BioTrue Daily                 90 Pack",          "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTrue Daily                 90pk",             "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTrue Daily                 Ninety Pac",       "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTrue Daily                 Ninety Pack",      "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTrue Daily                 Ninety Pack, Fi",  "BIOTRUE ONEDAY - 90 PACK" },
                { "BioTrue Daily                 Thirty Pack",      "BIOTRUE ONEDAY - 30 PACK" },
                { "BioTrue Daily                 Trial",            "........*TRIAL* BIOTRUE ONEDAY - 5 PACK" },
                { "BioTrue Daily                 Trials",           "........*TRIAL* BIOTRUE ONEDAY - 5 PACK" },
                { "BioTrueDailyTor               Ninety Pack",      "BIOTRUE ONEDAY TOR-90PK(3 THIRTIES)" },
                { "BioTrueDailyTor               Thirty Pack",      "BIOTRUE ONEDAY TORIC - 30 PACK" },
                { "BioTrueDailyTor               Trial",            "........*TRIAL* BIOTRUE 1DAY TORIC - 5 PACK" },
                { "clariti 1D MF                 Thirty Pack",      "CLARITI 1DAY MULTIFOCAL 30-PK" },
                { "clariti 1D MF                 Trial",            "........*TRIAL* CLARITI 1DAY MULTIFOCAL PK" },
                { "Clariti 1Day                  Ninety Pack",      "CLARITI 1DAY SPHERE 90-PK" },
                { "Clariti 1Day                  Trial",            "........*TRIAL* CLARITI 1DAY SPHERE 10-PK" },
                { "Clariti 1Day mf               Thirty Pack",      "CLARITI 1DAY MULTIFOCAL 30-PK" },
                { "Clariti 1Day MF               Trial",            "........*TRIAL* CLARITI 1DAY MULTIFOCAL PK" },
                { "Clariti 1Day mf               Trial",            "........*TRIAL* CLARITI 1DAY MULTIFOCAL PK" },
                { "Clariti 1DayMF                Ninety Pack",      "CLARITI 1DAY MULTIFOCAL 90-PK" },
                { "Clariti1DyToric               Ninety Pack",      "CLARITI 1DAY TORIC 90-PK" },
                { "Clariti1DyToric               T?hirty Pack",     "CLARITI 1DAY TORIC 30-PK" },
                { "Clariti1DyToric               Trial",            "........*TRIAL* CLARITI 1DAY TORIC 5-PACK" },
                { "Clearsight                    Trial",            "........*TRIAL* CLEARSIGHT 1-DAY TRIAL PK" },
                { "Clearsight 1 Da               Ninety Pack",      "CLEARSIGHT 1-DAY - 90 PACK" },
                { "C-Vue Multifoca               Six Packs",        "CVUE MULTIFOCAL - 6 PACK" },
                { "Dailies Total1                1 Lens",           "........*TRIAL* DAILIES TOTAL 1 TRIAL 5 CT" },
                { "Dailies Total1                90 Pack",          "DAILIES TOTAL 1 (ONE)- 90 PACK" },
                { "Dailies Total1                Ninety Pack",      "DAILIES TOTAL 1 (ONE)- 90 PACK" },
                { "Dailies Total1                Ninety Pack,",     "DAILIES TOTAL 1 (ONE)- 90 PACK" },
                { "Dailies Total1                Thirty Pack",      "DAILIES TOTAL 1 (ONE) - 30 PK" },
                { "Dailies Total1                Trial",            "........*TRIAL* DAILIES TOTAL 1 TRIAL 5 CT" },
                { "Dailies Totl1MF               Ninety Pack",      "DAILIES TOTAL 1 MULTIFOCAL - 90 PK" },
                { "Dailies Totl1MF               Thirty Pack",      "DAILIES TOTAL 1 MULTIFOCAL - 30 PK" },
                { "Dailies Totl1MF               Trial",            "........*TRIAL* DAILIES TOTAL 1 MF - 5CT" },
                { "Extreem H2Othin               Six Packs",        "HYDROGEL EXTREME H2O 59% THIN - 6PK" },
                { "Extreme H20 54                Six Packs",        "HYDROGEL EXTREME H2O 54% - 6 PACK" },
                { "Foc Toric Daily               Thirty Pack",      "FOCUS DAILIES - 30 PK" },
                { "FocusDailies                  90 Pack",          "FOCUS DAILIES - 90 PK" },
                { "FocusDailies                  Ninety Pack",      "FOCUS DAILIES - 90 PK" },
                { "FocusDailies                  Thirty Pack",      "FOCUS DAILIES - 30 PK" },
                { "FocusDailies                  Trial",            "........*TRIAL* FOCUS DAILIES - 5 CT" },
                { "FocusDailies To               90 Pack",          "FOCUS DAILIES - 90 PK" },
                { "Freq 55 Asph                  Six Packs",        "FREQUENCY 55 (GOLD) ASPHERIC - 6 PK" },
                { "Freq 55 Asph                  Trial",            "........*TRIAL* FREQUENCY ASPHERIC - 3 CT" },
                { "Frlk Clr Blends               Six Packs",        "FRESHLOOK COLORBLENDS - 6 PACK" },
                { "Frlk Clr Blends               Trial",            "........*TRIAL* FRESHLOOK COLORBLENDS 6 CT" },
                { "Frlk Colors                   Six Packs",        "FRESHLOOK COLORS - 6 PACK" },
                { "Frlk Dimensions               Six Packs",        "FRESHLOOK DIMENSIONS - 6 PACK" },
                { "Gothika Theatri               1 Lens",           "GOTHIKA THEATRICAL(HALLOWEEN) VIAL" },
                { "Hydrasoft toric               1 Lens",           "HYDRASOFT TORIC THIN SINGLE VIAL" },
                { "MyDay                         Ninety Pack",      "MYDAY DAILY DISPOSABLE 90 PK" },
                { "MyDay                         Trial",            "........*TRIAL* MYDAY 1-DAY TRIAL 10 PK" },
                { "Night & Day                   Six Packs",        "AIR OPTIX NIGHT & DAY - 6 PACK" },
                { "Oasys                         Twentyfour Pack",  "OASYS - 24 PK" },
                { "Phantom                       1 Lens",           "EYEDIA CLEARCOLOR PHANTOM VIALS" },
                { "PrClr 1 Day                   90 Pack",          "PROCLEAR 1 DAY - 90 PACK" },
                { "PrClr 1 Day                   Ninety Pack",      "PROCLEAR 1 DAY - 90 PACK" },
                { "PrClr 1 Day                   Trial",            "........*TRIAL* PROCLEAR 1-DAY - 10 PACK" },
                { "PrClr 1Day MF                 Ninety Pack",      "PROCLEAR 1 DAY MULTIFOCAL - 90 PK" },
                { "PrClr 1Day MF                 Thirty Pack",      "PROCLEAR 1 DAY MULTIFOCAL - 30 PK" },
                { "PrClr 1Day MF                 Trial",            "........*TRIAL* PROCLEAR 1DAY MULTIFOCAL PK" },
                { "PrClr MF                      Six Packs",        "PROCLEAR MULTIFOCAL - 6 PACK" },
                { "PrClr MF                      Trial",            "........*TRIAL* PROCLEAR MULTIFOCAL" },
                { "PrClr Sphere                  Six Packs",        "PROCLEAR SPHERE - 6 PACK" },
                { "PrClr Sphere                  Trial",            "........*TRIAL* PROCLEAR - 3 CT" },
                { "PrClr Toric                   Six Packs",        "PROCLEAR TORIC - 6 PK" },
                { "PrClr Toric                   Trial",            "........*TRIAL* PROCLEAR TORIC" },
                { "PrClr Toric MF                Six Packs",        "PROCLEAR MULTIFOCAL TORIC - 6 PACK" },
                { "PrClr Toric MF                Trial",            "........*TRIAL* PROCLEAR MULTIFOCAL TORIC" },
                { "PrClr Toric MFT               Six Packs",        "PROCLEAR MULTIFOCAL TORIC - 6 PACK" },
                { "PrClr Toric MFT               Trial",            "........*TRIAL* PROCLEAR MULTIFOCAL TORIC" },
                { "PrClr Toric XR                Six Packs",        "PROCLEAR TORIC XR - 6 PACK" },
                { "PrClr Toric XR                Trial",            "........*TRIAL* PROCLEAR TORIC XR" },
                { "PrClrtoric XR                 Trial",            "........*TRIAL* PROCLEAR TORIC XR" },
                { "Proc l daily MF               Ninety Pack",      "PROCLEAR 1 DAY MULTIFOCAL - 90 PK" },
                { "Proc l daily MF               Trial",            "........*TRIAL* PROCLEAR 1DAY MULTIFOCAL PK" },
                { "Proclear                      Six Packs",        "PROCLEAR SPHERE - 6 PACK" },
                { "Proclear                      Trial",            "........*TRIAL* PROCLEAR 1-DAY - 10 PACK" },
                { "Proclear sphere               Six Packs",        "PROCLEAR SPHERE - 6 PACK" },
                { "Proclear sphere               Trial",            "........*TRIAL* PROCLEAR - 3 CT" },
                { "Proclear Toric                Six Packs",        "PROCLEAR TORIC - 6 PK" },
                { "Proclear toric                Six Packs",        "PROCLEAR TORIC - 6 PK" },
                { "ProClTXR                      Trial",            "........*TRIAL* PROCLEAR TORIC XR" },
                { "Purevision                    Six Packs",        "PUREVISION 6 PACK" },
                { "Purevision                    Trial",            "........*TRIAL* PUREVISION" },
                { "Purevision 2 HD               Six Packs",        "PUREVISION 2 TORIC HD OPTICS - 6 PK" },
                { "Purevision 2 HD               Trial",            "........*TRIAL* PUREVISION 2 TORIC WITH HD" },
                { "Purevision MF                 Six Packs",        "PUREVISION MULTIFOCAL - 6 PACK" },
                { "Purevision MF                 Trial",            "........*TRIAL* PUREVISION MULTIFOCAL" },
                { "Purevision Tori               Six Packs",        "PUREVISION TORIC - 6 PACK" },
                { "Purevision Tori               Trial",            "........*TRIAL* PUREVISION TORIC" },
                { "PV2 For Astig                 Six Packs",        "PUREVISION TORIC - 6 PACK" },
                { "PV2 For Astig                 Trial",            "........*TRIAL* PUREVISION TORIC" },
                { "Soflens 38                    Six Packs",        "SOFLENS 38 - 6 PACK" },
                { "Soflens 38                    Trial",            "........*TRIAL* SOFLENS 38" },
                { "SofLens 66Toric               Six Packs",        "SOFLENS 66 TORIC - 6 PACK" },
                { "SofLens Daily                 90 Pack",          "SOFLENS DAILY DISPOSABLE - 90 PACK" },
                { "SofLens Daily                 Ninety Pack",      "SOFLENS DAILY DISPOSABLE - 90 PACK" },
                { "SofLens Daily                 Ninety Pack, Fi",  "SOFLENS DAILY DISPOSABLE - 90 PACK" },
                { "SofLens Daily                 Trail",            "........*TRIAL* SOFLENS DAILY - 5 PACK" },
                { "SofLens Daily                 Trial",            "........*TRIAL* SOFLENS DAILY - 5 PACK" },
                { "SofLens Daily T               Thirty Pack",      "SOFLENS DAILY TORIC - 30 PACK" },
                { "SofLens Daily T               Trial",            "........*TRIAL* SOFLENS DAILY TORIC PACK" },
                { "SofLens DailyTo               Thirty Pack",      "SOFLENS DAILY TORIC - 30 PACK" },
                { "SofLens Multi                 Six Packs",        "SOFLENS MULTIFOCAL - 6 PACK" },
                { "SofLens Multi                 Trial",            "........*TRIAL* SOFLENS MULTIFOCAL" },
                { "SofLens Tor Dly               Trial",            "........*TRIAL* SOFLENS DAILY TORIC PACK" },
                { "SofLens Toric                 Trial",            "........*TRIAL* SOFLENS DAILY TORIC PACK" },
                { "Softlens 1 Day                90 Pack",          "SOFLENS DAILY DISPOSABLE - 90 PACK" },
                { "Softlens 1 Day                Trial",            "........*TRIAL* SOFLENS DAILY - 5 PACK" },
                { "Softlens 66 Tor               Six Packs",        "SOFLENS 66 TORIC - 6 PACK" },
                { "Softlens 66 Tor               Trial",            "........*TRIAL* SOFLENS 66 TORIC" },
                { "Tru Eyes                      90 Pack",          "1 DAY ACUVUE TRUEYE - 90PK" },
                { "Tru Eyes                      Ninety Pack",      "1 DAY ACUVUE TRUEYE - 90PK" },
                { "Tru Eyes                      Trial",            "........*TRIAL* 1 DAY TRUEYE *TRIAL* 10PK" },
                { "Tru Eyes 90 Pak               90 Pack",          "1 DAY ACUVUE TRUEYE - 90PK" },
                { "Tru Eyes 90 Pak               Trial",            "........*TRIAL* 1 DAY TRUEYE *TRIAL* 10PK" },
                { "Ultra                         Six Packs",        "ULTRA - 6 PK" },
                { "Ultra                         Trial",            "........*TRIAL* B&L ULTRA SINGLE TRIAL" },
                { "Ultra For Astig               Six Packs",        "ULTRA FOR ASTIGMATISM - 6 PK" },
                { "Ultra For Astig               Trial",            "........*TRIAL* ULTRA FOR ASTIGMATISM" },
                { "Ultra Toric                   Trial",            "........*TRIAL* ULTRA FOR ASTIGMATISM" },
                { "Vertex Torics                 Six Packs",        "VERTEX TORIC - 6 PACK" },
                { "Vita astig                    Trial",            "........*TRIAL* ACUVUE VITA FOR ASTIGMATISM" },
                { "Vitality                      Six Packs",        "AVAIRA VITALITY 6-PK" },
                { "Vitality                      Trial",            "........*TRIAL* AVAIRA VITALITY SINGLE" },
                { "Vitality toric                Six Packs",        "AVAIRA TORIC - 6-PACK" },
                { "Vitality toric                Trial",            "........*TRIAL* AVAIRA VITALITY TORIC - 1PK" },
                { "1 Day AV                      Ninety Pack",      "1 DAY ACUVUE MOIST - 90 PACK" },
                { "1D AV                         Ninety Pack",      "1 DAY ACUVUE MOIST - 90 PACK" },
                { "Air Op Mo                     Six Packs",        "AIR OPTIX SPHERE - 6 PK" },
                { "AV Oasys                      Ninety Pack",      "1 DAY ACUVUE OASYS HYDRALUXE 90PK" },
                { "AV Oasys 1 Day                Ninety P",         "1 DAY ACUVUE OASYS HYDRALUXE 90PK" },
                { "AV Oasys 1 Day                Ninety Pack",      "1 DAY ACUVUE OASYS HYDRALUXE 90PK" },
                { "BioTrue Daily                 Six Packs",        "........*TRIAL* BIOTRUE ONEDAY - 5 PACK" },
                { "Clariti 1DayMF                3-30 Pack Bundl",  "CLARITI 1DAY MULTIFOCAL 90-PK" },
                { "Frlk Visi                     Trial",            "........*TRIAL* FRESHLOOK LITE TINT - 6 CT" },
                { "HydrsfTor DW I                Trial",            "HYDRASOFT TORIC THIN SINGLE VIAL" },
                { "PreferenceToric               Trial",            "PREFERENCE TORIC 4-PACK VIAL" },
                { "Purevision 2                  Six Packs",        "PUREVISION 2 TORIC HD OPTICS - 6 PK" },
                { "Purevision 2                  Trial",            "........*TRIAL* PUREVISION 2 WITH HD OPTICS" },
                { "Purevision 2 MF               Six Packs",        "PUREVISION 2 FOR PRESBYOPIA - 6 PK" },
                { "Purevision 2 MF               Trial",            "........*TRIAL* PUREVISION 2 FOR PRESBYOPIA" },
                { "Purevision 2MF                Six Packs",        "PUREVISION 2 FOR PRESBYOPIA - 6 PK" },
                { "Purevision 2MF                Trial",            "........*TRIAL* PUREVISION 2 FOR PRESBYOPIA" },
                { "Purevision2 MF                Six Packs",        "PUREVISION 2 FOR PRESBYOPIA - 6 PK" },
                { "Purevision2 MF                Trial",            "........*TRIAL* PUREVISION 2 FOR PRESBYOPIA" },
                { "PV2 MF                        Six Packs",        "PUREVISION 2 FOR PRESBYOPIA - 6 PK" },
                { "PV2 MF                        Trial",            "........*TRIAL* PUREVISION 2 FOR PRESBYOPIA" },
                { "SofLens Toric                 Six Packs",        "........*TRIAL* SOFLENS DAILY - 5 PACK" },
                { "Total 1                       Ninety Pack",      "DAILIES TOTAL 1 (ONE)- 90 PACK" },
                { "Ultra MF                      Six Packs",        "ULTRA FOR PRESBYOPIA - 6 PK" },
                { "Ultra MF                      Trial",            "........*TRIAL* ULTRA FOR PRESBYOPIA TRIAL" },
                { "UltraMF                       Six Packs",        "ULTRA FOR PRESBYOPIA - 6 PK" },
                { "BioMed Premier                Trial",            "........*TRIAL* BIOMEDICS 55 ASPHERIC – 3CT" },
                { "SofLens Daily T               3/30 Pk Bundle",   "SOFLENS DAILY TORIC - 30 PACK" },
                { "SofLens Daily T               Three-Thirty Pk",  "SOFLENS DAILY TORIC - 30 PACK" },
                { "CLR CLR EYEDIA                1 Lens",           "EYEDIA CLEARCOLOR ELEMENTS - 6PK" },
                // { "", "" },
            };

            return CrossRefDictionary;
        }
    }
}
